name: eyeglasses-api
services:
  postgres:
    image: postgres:14
    container_name: eyeglasses-postgres
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'eyeglasses-api']
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_DB: eyeglasses-db
      POSTGRES_USER: eyeglasses
      POSTGRES_PASSWORD: eyeglasses

  # redis:
  #   image: redis
  #   ports:
  #     - 6365:6379
  #   healthcheck:
  #     test: ['CMD', 'redis-cli', 'ping']
  #     interval: 10s
  #     timeout: 30s
  #     retries: 3
