export enum EnumInjectServiceToken {
  AUTH_SERVICE = 'AUTH_SERVICE',
  USER_SERVICE = 'USER_SERVICE',
  PRODUCT_SERVICE = 'PRODUCT_SERVICE',
  CART_SERVICE = 'CART_SERVICE',
  CART_ITEM_SERVICE = 'CART_ITEM_SERVICE',
  ORDER_SERVICE = 'ORDER_SERVICE',
  STORE_INFO_SERVICE = 'STORE_INFO_SERVICE',
  COUPON_SERVICE = 'COUPON_SERVICE',
  ORDER_COUPON_SERVICE = 'ORDER_COUPON_SERVICE',
}
